const raceTiles = [
    {"race":"The Federation of Sol", "tilee":"1"},
    {"race":"The Mentak Coalition", "tilee":"2"},
    {"race":"The Yin Brotherhood", "tilee":"3"},
    {"race":"The Embers of Muaat", "tilee":"4"},
    {"race":"The Arborec", "tilee":"5"},
    {"race":"The Lizix Mindnet", "tilee":"6"},
    {"race":"The Winnu", "tilee":"7"},
    {"race":"The Nekro Virus", "tilee":"8"},
    {"race":"The Naalu Collective", "tilee":"9"},
    {"race":"The Barony of Letnev", "tilee":"10"},
    {"race":"The Clan of Saar", "tilee":"11"},
    {"race":"The Universities of Jol-Nar", "tilee":"12"},
    {"race":"Sardakk N'orr", "tilee":"13"},
    {"race":"The Xxcha Kingdom", "tilee":"14"},
    {"race":"The Yssaril Tribes", "tilee":"15"},
    {"race":"The Emirates of Hacan", "tilee":"16"},
    {"race":"The Ghosts of Creuss", "tilee":"17"},
    {"race":"ThThe Mahact Gene-sorcerers", "tilee":"52"},
    {"race":"The Mahact Gene-sorcerers", "tilee":"53"},
    {"race":"The Vuil'raith Cabal", "tilee":"54"},
    {"race":"The Titans of Ul", "tilee":"55"},
    {"race":"The Empyrean", "tilee":"56"},
    {"race":"The Naaz-Rokha Alliance", "tilee":"57"},
    {"race":"The Argent Flight", "tilee":"58"}
]

